# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import details_pb2 as details__pb2


class ArrayDetailsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Personal = channel.unary_stream(
                '/ArrayDetails/Personal',
                request_serializer=details__pb2.Details.SerializeToString,
                response_deserializer=details__pb2.Details.FromString,
                )


class ArrayDetailsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Personal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArrayDetailsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Personal': grpc.unary_stream_rpc_method_handler(
                    servicer.Personal,
                    request_deserializer=details__pb2.Details.FromString,
                    response_serializer=details__pb2.Details.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArrayDetails', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArrayDetails(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Personal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ArrayDetails/Personal',
            details__pb2.Details.SerializeToString,
            details__pb2.Details.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
